[build]
  command = "remix build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

# [[plugins]]
#   package = "@netlify/plugin-lighthouse"

#   [[plugins.inputs.audits]]
#     url = "https://remix.mel.quest/"


[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    path = "route1"
    [plugins.inputs.thresholds]
      performance = 0.9
      accessibility = 0.9
      best-practices = 0.9
      seo = 0.9
      pwa = 0.9